<?php
    $this->headTitle('Cover image');
    $form->setAttribute('id', 'upload-form')->setAttribute('action', $this->url('post', array('action' => 'cover')));
    $form->prepare();
?>
<div class="alert alert-success" id="alertbox">
    <div class="container-fluid">
        <div class="alert-icon">
            <i class="material-icons">check</i>
        </div>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true"><i class="material-icons">clear</i></span>
        </button>
        <b>Success Alert:</b> Your photo was successfully saved!
    </div>
</div>
<div class="col-lg-9">
    <div class="section text-center section-landing">
        <h2 class="text-info">Please upload cover photo</h2>
        <p>Please do it and make your post look nicer!</p>
        <hr>
    </div>

    <div class="section">
        <img class="img-responsive preview" src="" id="image">
        <input type="hidden" id="id" name="id" value="<?= $id ?>">
        <?= $this->form()->openTag($form) ?>
        <?= $this->formRow($form->get('cover-file')) ?>
        <br>
        <button type="submit" id="freak" class="btn btn-round btn-primary pull-right"><i class="material-icons">more</i> Crop</button>
        <?= $this->form()->closeTag() ?> 
    </div>

</div>