<div class="section section-landing">
    <div class="avatar">
        <img class="img-responsive img-rounded img-raised center-block" src="<?= $this->basepath('../public/img/no-cover.png') ?>">
    </div>
    <h2 class="text-center">"Username Here"</h2>
    <h6 class="text-center text-uppercase">occupation</h6>
    <p class="text-center description">About paragraph</p>
    <hr>

    <div class="section section-landing">
        <h2></h2>
    </div>
</div>