<?php
  //$form->setAttribute('action', 'edit');
  $form->prepare();
 ?>


 <div class="col-lg-10 col-lg-offset-1">
 <div class="section section-landing">
     <div class="row">
         <h2 class="title">Edit post</h2>
         <?= $this->form()->openTag($form); ?>
         <div class="form-group">
             <?= $this->formHidden($form->get('id')); ?>
         </div>

         <div class="col-lg-6">
             <div class="form-group label-floating">
                 <label class="control-label">
                     <?= $this->formLabel($form->get('title')) ?>
                 </label>
                 <?= $this->formInput($form->get('title')) ?>
             </div>
         </div>

         <div class="col-lg-6">
             <div class="form-group label-floating">
                 <label class="control-label">
                     <?= $this->formLabel($form->get('price')) ?>
                 </label>
                 <?= $this->formInput($form->get('price')) ?>
             </div>
         </div>

         <div class="col-lg-6">
             <div class="form-group label-floating">
                 <label class="control-label">
                     <?= $this->formLabel($form->get('phone')) ?>
                 </label>
                 <?= $this->formInput($form->get('phone')) ?>
             </div>
         </div>

         <div class="col-lg-6">
             <div class="form-group label-floating">
                 <label class="control-label">
                     <?= $this->formLabel($form->get('email')) ?>
                 </label>
                 <?= $this->formInput($form->get('email')) ?>
             </div>
         </div>

         <div class="col-lg-6">
             <div class="form-group label-floating">
                 <label class="control-label">
                     Category
                 </label>
                 <?= $this->formSelect($form->get('category_id')) ?>
             </div>
         </div>

         <br><br>
         <div class="col-lg-12">
             <div class="form-group label-floating">
                 <label class="control-label">
                     <?= $this->formLabel($form->get('description')) ?>
                 </label>
                 <?= $this->formTextarea($form->get('description')) ?>
             </div>
         </div>


         <button class="btn btn-round btn-info btn-block pull-right" type="submit"><i class="material-icons">update</i> Update</button>
         <?= $this->form()->closeTag(); ?>
     </div>
 </div>
 </div>
