<?php
    $this->headTitle("Index page man");
?>
    <?php foreach ($posts as $post) : ?>
        <div class="card" style="width: 300px; overflow: hidden; margin-left: 10px;">
            <?php
                if ($post->cover) {
            ?>
                <img class="card-img-top" src="<?= $this->basepath('../data/uploads/posts/' . $post->cover) ?> " alt="<?= $post->title ?>">
            <?php

                } else {
            ?>com
                <img class="card-img-top" src="<?= $this->basepath('/img/no-cover.png') ?>" alt="Card image cap">
            <?php

                }
            ?>
            <div class="card-block" style="padding: 10px;">
                <h4 class="card-title"><?= $post->title ?></h4>
                <p class="card-text"><?= $post->description ?>.</p>
                <a href="#" class="btn btn-primary">More <i class="material-icons">more</i></a>
            </div>
        </div>
    <?php endforeach; ?>