<?php
    $this->headTitle("Index page man");
?>

    <?php foreach ($this->paginator as $post) : ?>
        <div class="card" style="width: 300px; overflow: hidden; margin-left: 10px;">
            <?php
                if ($post->cover) {
            ?>
                <img class="card-img-top" src="<?= $this->basepath('../data/uploads/posts/' . $post->cover) ?> " alt="<?= $post->title ?>">
            <?php

                } else {
            ?>
                <img class="card-img-top" src="<?= $this->basepath('/img/no-cover.png') ?>" alt="Card image cap">
            <?php
                }

            ?>
            <div class="card-block" style="padding: 10px;">
                <h4 class="card-title"><?= $post->title ?></h4>
                <p class="card-text"><?= $post->description ?>.</p>
                <a href="<?= $this->url('post', array('action' => 'display', 'id' => $post->id)) ?>" class="btn btn-primary">More <i class="material-icons">more</i></a>
            </div>
        </div>
    <?php endforeach; ?>

<?php
    // add at the end of the file after the table
    echo $this->paginationControl(
    // the paginator object
        $this->paginator,
        // the scrolling style
        'sliding',
        // the partial to use to render the control
        'partial/paginator.phtml',
        // the route to link to when a user clicks a control link
        array(
            'route' => 'post'
        )
    );
?>
