<?php

    $this->headTitle("Add new profile");
    $form->setAttribute('action', $this->url('profile', array('action' => 'add')));
    $form->prepare();
?>
    <div class="col-lg-8 well">
        <h4 class="text-info text-center">Add new profile</h4>
    <?= $this->form()->openTag($form) ?>
    <div class="form-group label-floating">
        <label class="control-label">
            <?= $this->formLabel($form->get('username')) ?>
        </label>
        <?= $this->formInput($form->get('username')) ?>
    </div>

    <div class="form-group label-floating">
        <label class="control-label">
            <?= $this->formLabel($form->get('firstname')) ?>
        </label>
        <?= $this->formInput($form->get('firstname')) ?>
    </div>

    <div class="form-group label-floating">
        <label class="control-label">
            <?= $this->formLabel($form->get('lastname')) ?>
        </label>
        <?= $this->formInput($form->get('lastname')) ?>
    </div>

    <div class="form-group label-floating">
        <label class="control-label">
            <?= $this->formLabel($form->get('mobile')) ?>
        </label>
        <?= $this->formInput($form->get('mobile')) ?>
    </div>

    <div class="form-group label-floating">
        <label class="control-label">
            <?= $this->formLabel($form->get('interests')) ?>
        </label>
        <?= $this->formInput($form->get('interests')) ?>
    </div>

    <div class="form-group label-floating">
        <label class="control-label">
            <?= $this->formLabel($form->get('occupation')) ?>
        </label>
        <?= $this->formInput($form->get('occupation')) ?>
    </div>

    <div class="form-group label-floating">
        <label class="control-label">
            <?= $this->formLabel($form->get('about')) ?>
        </label>
        <?= $this->formTextarea($form->get('about')) ?>
    </div>

    <?= $this->formRow($form->get('image-file')) ?>
        <img class="img-responsive img-rounded preview" src="" alt="">
    <div class="form-group">
        <button class="btn btn-warning btn-round pull-right" type="submit">Save Changes</button>
    </div>



    <?= $this->form()->closeTag() ?>
</div>