<?php
    $this->headTitle($profile->username . ' Profile page');
?>
<div class="col-lg-9 main main-raised">
<div class="section section-landing">
    <div class="avatar">
        <?php if ($profile->image) { ?>
            <img class="img-responsive img-rounded img-raised center-block" src="<?= $this->basepath('../data/uploads/profile/' . $profile->image) ?>">
        <?php } else { ?>
            <img class="img-responsive img-rounded img-raised center-block" src="<?= $this->basepath('/img/profilepic.png') ?>">
        <?php } ?>
    </div>
    <h2 class="text-center"><?= $profile->firstname . ' ' . $profile->lastname . '<br> A.K.A <br>  ' . $profile->username ?></h2>
    <h6 class="text-center text-uppercase"><?= $profile->occupation ?></h6>
    <p class="text-center description"><?= $profile->about ?></p>
    <hr>

    <div class="section section-landing">
        <h5 class="text-center text-uppercase"><?= $profile->username ?> influence</h5>

        <div class="profile-tabs">
            <div class="nav-align-center">
                <ul class="nav nav-pills">
                    <li class="active">
                        <a class="" data-toggle="tab" href="#posts">Posts</a>
                    </li>
                    <li>
                        <a class="" data-toggle="tab" href="#wow">Wow</a>
                    </li>
                </ul>

                <div class="tab-content">
                    <div class="tab-pane" id="posts">
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quae quisquam suscipit vel! At atque aut autem doloremque ea facilis impedit, laudantium molestias neque quasi reiciendis, saepe ut veniam, veritatis vitae.</p>
                    </div>
                    <div class="tab-pane" id="wow">
                        <p>another Lorem ipsum dolor sit amet, consectetur adipisicing elit. Laborum neque odit omnis reprehenderit sapiente tempora tenetur? Accusamus at autem, hic iste itaque labore nemo nesciunt, rem, saepe sit vero voluptatibus!</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</div>

<div class="col-lg-3 main main-raised">
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Esse fugiat, labore. Ad aliquam animi architecto, asperiores at dolore doloribus earum exercitationem in ipsam, laudantium minima perspiciatis quas repellat saepe, voluptatem.</p>
</div>