<?php
    $profileForm->setAttribute('action', $this->url('profile', array('action' => 'edit')));
    $profileForm->prepare();
    $imageForm->setAttribute('action', $this->url('profile', array('action' => 'upload')));
    $imageForm->setAttribute('id', 'myForm');
    $imageForm->prepare();
?>
<br><br>

<div class="card card-nav-tabs">
    <div class="header header-success">
        <!-- colors: "header-primary", "header-info", "header-success", "header-warning", "header-danger" -->
        <div class="nav-tabs-navigation">
            <div class="nav-tabs-wrapper">
                <ul class="nav nav-tabs" data-tabs="tabs">
                    <li class="">
                        <a href="#profile" data-toggle="tab" aria-expanded="false">
                            <i class="fa fa-user"></i>
                            Informations
                            <div class="ripple-container"></div></a>
                    </li>
                    <li class="active">
                        <a href="#messages" data-toggle="tab" aria-expanded="true">
                            <i class="fa fa-camera-retro"></i>
                            Avatar
                            <div class="ripple-container"></div></a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <div class="content" style="overflow: hidden">
        <div class="tab-content text-center">
            <div class="tab-pane" id="profile">
                <div class="col-lg-8 col-lg-offset-2">
                    <?= $this->form()->openTag($profileForm); ?>
                    <?= $this->formHidden($profileForm->get('id')) ?>
                    <div class="form-group label-floating">
                        <label class="control-label">
                            <?= $this->formLabel($profileForm->get('username')) ?>
                        </label>
                        <?= $this->formInput($profileForm->get('username')) ?>
                    </div>

                    <div class="form-group label-floating">
                        <label class="control-label">
                            <?= $this->formLabel($profileForm->get('firstname')) ?>
                        </label>
                        <?= $this->formInput($profileForm->get('firstname')) ?>
                    </div>

                    <div class="form-group label-floating">
                        <label class="control-label">
                            <?= $this->formLabel($profileForm->get('lastname')) ?>
                        </label>
                        <?= $this->formInput($profileForm->get('lastname')) ?>
                    </div>

                    <div class="form-group label-floating">
                        <label class="control-label">
                            <?= $this->formLabel($profileForm->get('mobile')) ?>
                        </label>
                        <?= $this->formInput($profileForm->get('mobile')) ?>
                    </div>

                    <div class="form-group label-floating">
                        <label class="control-label">
                            <?= $this->formLabel($profileForm->get('interests')) ?>
                        </label>
                        <?= $this->formInput($profileForm->get('interests')) ?>
                    </div>

                    <div class="form-group label-floating">
                        <label class="control-label">
                            <?= $this->formLabel($profileForm->get('occupation')) ?>
                        </label>
                        <?= $this->formInput($profileForm->get('occupation')) ?>
                    </div>

                    <div class="form-group label-floating">
                        <label class="control-label">
                            <?= $this->formLabel($profileForm->get('about')) ?>
                        </label>
                        <?= $this->formTextarea($profileForm->get('about')) ?>
                    </div>

                    <button type="submit" class="btn btn-info btn-round btn-block"><i class="fa fa-save"></i> Save Changes</button>
                    <?= $this->form()->closeTag(); ?>
                </div>

            </div>
            <div class="tab-pane active" id="messages">
                <div class="col-lg-6 col-lg-offset-3">

                    <img class="img-responsive preview" src="<?= $this->basepath('../data/uploads/profile/' . $profile->image) ?>" id="image-file">
                    <?= $this->form()->openTag($imageForm); ?>
                    <div class="">
                        <label class="control-label"><i class="material-icons">face</i></label>
                        <?= $this->formRow($imageForm->get('image-file')) ?>
                    </div>
                    <button type="submit" class="btn btn-info btn-round btn-block">
                        <i class="fa fa-save"></i>
                        Save
                    </button>
                    <?= $this->form()->closeTag(); ?>
                </div>

            </div>
            </div>
        </div>
    </div>
