<?php
    $auth = new \Zend\Authentication\AuthenticationService();
    $form->setAttribute('action', $this->url('post', array('action' => 'search')));
    $form->setAttribute('class', 'navbar-form');
    $form->prepare();
    echo $this->doctype();
?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Fabour '. $this->translate('Welcome'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons" />
        <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700" />
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" />
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/font-awesome.min.css')
                        ->prependStylesheet($this->basePath() . '/css/font-awesome.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
            //->prependStylesheet($this->basePath() . '/css/demo.css')
            ->prependStylesheet($this->basePath() . '/css/cropper.css')
            ->prependStylesheet($this->basePath() . '/css/material-kit.css') ?>

        <?php echo $this->headScript()
                ->appendFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                ->appendFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
                ->appendFile($this->basePath() . '/js/jquery.min.js')
                ->appendFile($this->basePath() . '/js/bootstrap.min.js')
                ->appendFile($this->basePath() . '/js/cropper.js')
                ->appendFile($this->basePath() . '/js/app.js')
                ->appendFile($this->basePath() . '/js/material.min.js')
            ->appendFile($this->basePath() . '/js/material-kit.js')
            //<!-- Scripts -->
        ; ?>

    </head>
    <body>
    <?php if ($auth->hasIdentity()) {?>
        <nav class="navbar navbar-primary">
            <div class="container">
                <!-- Brand and toggle get grouped for better mobile display -->
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navigation-example">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?= $this->url('post', array('action' => 'index')) ?>">MyZendApp</a>
                </div>

                <div class="collapse navbar-collapse" id="navigation-example">
                    <ul class="nav navbar-nav">

                        <li>
                            <a href="<?= $this->url('post', array('action' => 'add')) ?>"> Add Post
                            </a>
                        </li>
                        <li>
                            <a href="<?= $this->url('profile', array('action' => 'display')) ?>"> Add Profile
                            </a>
                        </li>
                    </ul>
                    <div class="col-sm-6 col-md-6">
                        <?= $this->form()->openTag($form) ?>
                            <div class="input-group">
                                <?= $this->formRow($form->get('search')) ?>
                                <div class="input-group-btn">
                                    <button class="btn btn-round btn-default" type="submit"><i class="material-icons">search</i></button>
                                </div>
                            </div>
                        <?= $this->form()->closeTag(); ?>
                    </div>
                    
                    <ul class="nav navbar-nav">
                        <li>
                            <a href="<?php $this->url('profile',array('action' => 'display', 'id' => $profile->id)) ?>">
                                <i class="material-icons">face</i><strong><?= $profile->username ?></strong>
                            </a>
                        </li>
                        <li>
                            <a href="<?= $this->url('zfcuser/logout') ?>"><i class="material-icons">redo</i>Logout</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    <?php } else { ?>
        <nav class="navbar navbar-info">
            <div class="container">
                <!-- Brand and toggle get grouped for better mobile display -->
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navigation-example">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?= $this->url('post', array('action' => 'index')) ?>">MyZendApp</a>
                </div>

                <div class="collapse navbar-collapse" id="navigation-example">
                    <ul class="nav navbar-nav pull-right">

                        <li>
                            <a href="<?php $this->url('zfcuser/login') ?>"><i class="material-icons">input</i> LOGIN
                            </a>
                        </li>
                        <li>
                            <a href="<?= $this->url('zfcuser/register') ?>" ><i class="material-icons">open_in_browser</i> REGISTER
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    <?php } ?>


    <?php $this->partial('partial/search');  ?>
        <?php
            //This needs to be a search bar
        ?>
        <br><br>
    <div class="col-lg-9">
        <div class="main main-raised" style="margin-top: 0px;">
            <div class="container">
                <div class="col-lg-9">
                    <?php echo $this->content; ?>
                </div>
            </div>
        </div>
    </div>

    <div class="col-lg-3">
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab, ad consequatur cum cumque deserunt dolorem eaque eligendi facere impedit incidunt nihil odit officia qui quia quisquam, ratione unde? Incidunt, quibusdam?</p>
    </div>
    <hr>
        <div class="clearfix"></div>
    <footer>
        <p class="text-center"> Copyright &copy; 2015 - <?php echo date('Y') ?> Fabour <?php echo $this->translate('All rights reserved.') ?></p>
    </footer>

        <?php echo $this->inlineScript() ?>
    </body>
</html>
