<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Fabour '. $this->translate('Welcome'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
                        //->prependStylesheet($this->basePath() . '/css/demo.css')
                        ->prependStylesheet($this->basePath() . '/css/material-kit.css') ?>

        <?php echo $this->headScript()
                ->prependFile($this->basePath() . '/js/jquery.min.js')
                ->prependFile($this->basePath() . '/js/bootstrap.min.js')
                ->prependFile($this->basePath() . '/js/material.min.js')
                ->prependFile($this->basePath() . '/js/material-kit.js')
                ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
            //<!-- Scripts -->
        ; ?>

    </head>
    <body>
        <nav class="navbar"  >
            <div class="container">
                <!-- Brand and toggle get grouped for better mobile display -->
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navigation-example">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="#">Fabour</a>
                </div>

                <div class="collapse navbar-collapse" id="navigation-example">
                    <ul class="nav navbar-nav">
                        <li>
                            <a href="#" target="_blank">
                                Components
                            </a>
                        </li>
                        <li>
                            <a href="#" target="_blank"> Add Post
                            </a>
                        </li>
                        <li>
                            <a href="#" target="_blank"> Add Post
                            </a>
                        </li>
                        <li>
                            <a href="#" target="_blank"> Add Post
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        <br><br>
        <div class="container" STYLE="margin-top: 20px;">
            <div class="main main-raised">
                <div class="container">
                    <?php echo $this->content; ?>
                </div>
            </div>

            <hr>
            <footer>
                <p> Copyright &copy; 2015 - <?php echo date('Y') ?> Fabour <?php echo $this->translate('All rights reserved.') ?></p>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
