<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Fabour '. $this->translate('Welcome'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons" />
        <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700" />
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" />
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/font-awesome.min.css')
                        ->prependStylesheet($this->basePath() . '/css/font-awesome.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
            //->prependStylesheet($this->basePath() . '/css/demo.css')
            ->prependStylesheet($this->basePath() . '/css/cropper.css')
            ->prependStylesheet($this->basePath() . '/css/material-kit.css') ?>

        <?php echo $this->headScript()
                ->appendFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                ->appendFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
                ->appendFile($this->basePath() . '/js/jquery.min.js')
                ->appendFile($this->basePath() . '/js/bootstrap.min.js')
                ->appendFile($this->basePath() . '/js/cropper.js')
                ->appendFile($this->basePath() . '/js/app.js')
                ->appendFile($this->basePath() . '/js/material.min.js')
                ->appendFile($this->basePath() . '/js/material-kit.js')
            //<!-- Scripts -->
        ; ?>

    </head>
    <body>
        <nav class="navbar navbar-info">
            <div class="container">
                <!-- Brand and toggle get grouped for better mobile display -->
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navigation-example">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="#">MyZendApp</a>
                </div>

                <div class="collapse navbar-collapse" id="navigation-example">
                    <ul class="nav navbar-nav">
                        <li>
                            <a href="#" target="_blank">
                                Components
                            </a>
                        </li>
                        <li>
                            <a href="<?= $this->url('post', array('action' => 'add')) ?>" target="_blank"> Add Post
                            </a>
                        </li>
                        <li>
                            <a href="<?= $this->url('profile', array('action' => 'display')) ?>" target="_blank"> Add Profile
                            </a>
                        </li>
                        <li>
                            <a href="#" target="_blank"> Add Post
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        <br><br>

        <div class="main main-raised" style="margin-top: 0px;">
            <div class="container">
                <?php echo $this->content; ?>
            </div>
        </div>

        <hr>
        <footer>
            <p class="text-center"> Copyright &copy; 2015 - <?php echo date('Y') ?> Fabour <?php echo $this->translate('All rights reserved.') ?></p>
        </footer>

        <?php echo $this->inlineScript() ?>
    </body>
</html>
